networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Adsa2023
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
    ports:
      - '1433:1433'
    expose:
      - 1433
    volumes:
      - db:/var/opt/sqlserver/data
volumes:
  db:
    driver: local
