name: .NET Build and Test

on:
  push:
    branches: [ $default-branch, build-test-branch  ]
  pull_request:
    branches: [ $default-branch, build-test-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal