name: Release

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - $default-branch
      - feat-add_semantic_versioning
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
  
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Create Linux Release
        run: |
          dotnet publish -r linux-x64 --self-contained

          zip -r -j "Chirp.CLI-$tag-linux-x64.zip" src/Chirp.CLI/bin/Debug/net7.0/linux-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/linux-x64/publish/
      - name: Create Windows Release
        run: |
          dotnet publish -r win-x64 --self-contained

          zip -r -j "Chirp.CLI-$tag-windows-x64.zip" src/Chirp.CLI/bin/Debug/net7.0/linux-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/linux-x64/publish/
      - name: Create OSX x64 Release
        run: |
          dotnet publish -r osx-x64 --self-contained

          zip -r -j "Chirp.CLI-$tag-osx-x64.zip" src/Chirp.CLI/bin/Debug/net7.0/linux-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/linux-x64/publish/
      - name: Create OSX arm Release
        run: |
          dotnet publish -r osx-arm64 --self-contained

          zip -r -j "Chirp.CLI-$tag-osx-arm-x64.zip" src/Chirp.CLI/bin/Debug/net7.0/linux-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/linux-x64/publish/
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Chirp.CLI-${{ env.tag }}-linux-x64.zip
            Chirp.CLI-${{ env.tag }}-windows-x64.zip
            Chirp.CLI-${{ env.tag }}-osx-x64.zip
            Chirp.CLI-${{ env.tag }}-osx-arm-x64.zip
