name: Release

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - $default-branch
      - build-test-branch
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Create Linux Release
        run: |
          dotnet publish -r linux-x64 --self-contained
          zip -r linux-x64.zip src/Chirp.CLI/bin/Debug/net7.0/linux-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/linux-x64/publish/

      - name: Create Windows Release
        run: |
          dotnet publish -r win-x64 --self-contained
          zip -r win-x64.zip src/Chirp.CLI/bin/Debug/net7.0/win-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/win-x64/publish/

      - name: Create OSX x64 Release
        run: |
          dotnet publish -r osx-x64 --self-contained
          zip -r osx-x64.zip src/Chirp.CLI/bin/Debug/net7.0/osx-x64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/osx-x64/publish/

      - name: Create OSX arm Release
        run: |
          dotnet publish -r osx-arm64 --self-contained
          zip -r osx-arm64.zip src/Chirp.CLI/bin/Debug/net7.0/osx-arm64/publish/ src/Chirp.SimpleDB/bin/Debug/net7.0/osx-arm64/publish/

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux-x64.zip
            win-x64.zip
            osx-x64.zip
            osx-arm64.zip
